# This is where you define all of the routes exposed by each component
# Identify the Set (component) and then the paths available for testing

levels:
  1:
    cedilla:
      set: 'cedilla'
  
      roles: ['/'. '/citation']
  
  2:
    sfx_service:
      set: 'cedilla_services'
      roles: ['/sfx']
      
    oclc_xid_service:
      set: 'cedilla_services'
      roles: ['/oclc_xid']
      