environment_specific_configuration:
  cdl-cedilla:
    repository_uri: 'https://github.com/cdlib/cdl-cedilla.git'
    retrieval_command: 'git clone'

sets:
  cedilla:
    repository_uri: 'https://github.com/cdlib/cedilla.git'
    retrieval_command: 'git clone'
    build_command: 'npm install'  
    start_command: 'export NODE_PORT=3005 && nohup node cedilla.js > output.log &'
  
    pid_location: 'cedilla.pid'

    # The live port will be pulled out of the startup script and replaced with the mock port when mocking
    live_port: '3005'
    mock_port: '9005'
  
    # List all of the configuration file locations (relative to the project root) 
    # Rehearsal will swap out all live_targets in the config files with mock_targets
    # All other http targets will be change to point to the test proxy
    config_location: '/config'
    config_replacement: [{dir: '.', 
                          files: ['cdl-cedilla/cedilla/DEV/config/application.yaml',
                                  'cdl-cedilla/cedilla/DEV/config/rules.yaml',
                                  'cdl-cedilla/cedilla/DEV/config/services.yaml']},
                         {dir: './notifiers', 
                          files: ['cdl-cedilla/cedilla/DEV/config/email.yaml',
                                  'cdl-cedilla/cedilla/DEV/config/slack_irc.yml']}]

    # This should match the mock port of the component it will call
    rewrite_lines_for_mocking: [{from: 'http://localhost:3102', to: 'http://localhost:9102'},
                                {from: 'http://localhost:3101', to: 'http://localhost:9101'},
                                {from: 'http://localhost:8088', to: 'http://localhost:9103'}]

  cedilla_services:
    repository_uri: 'https://github.com/cdlib/cedilla_services.git'
    retrieval_command: 'git clone'
    build_command: 'bundle install'
    start_command: 'thin -R config.ru start -p 3101 -d'

    pid_location: 'tmp/pids/thin.pid'

    # The live port will be pulled out of the startup script and replaced with the mock port when mocking
    live_port: '3101'
    mock_port: '9101'
  
    # List all of the configuration file locations (relative to the project root) 
    # Rehearsal will swap out all live_targets in the config files with mock_targets
    # All other http targets will be change to point to the test proxy
    config_location: '/config'
    config_replacement: [{dir: '.', files: ['cdl-cedilla/cedilla_services/DEV/config/app.yml']}]
    
    # Using ALL here tells the system to rewrite ALL http/https entries to the specified address
    rewrite_lines_for_mocking: [{from: 'ALL', to: 'http://localhost:9099'}]